name: CI Pet Clinic App

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn clean package

      - name: Check if the .war exists
        run: ls target

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: petclinic
          path: target/petclinic.war

  publish:
    name: Publish petclinic
    needs: build
    if: github.event_name != 'pull_request'
    env:
      ARTIFACT_DIR: ./release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: download artifacts - petclinic
        uses: actions/download-artifact@master
        with:
          name: petclinic
          path: ${{ env.ARTIFACT_DIR }}

      - name: publish files to github
        if: startswith(github.ref, 'refs/tags/v')
        run: |
          echo "installing github-release-cli..."
          sudo npm install --silent --no-progress -g @babel/runtime
          sudo npm install --silent --no-progress -g github-release-cli
          # Get the list of files
          RELEASE_ARTIFACT=(${ARTIFACT_DIR}/*)
          # Parse repository to get owner and repo names
          OWNER_NAME="${GITHUB_REPOSITORY%%/*}"
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          REL_VERSION="5.3.1"
          RELEASE_BODY="This is the release candidate ${REL_VERSION}"
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          echo "Uploading files to GitHub Release"
          github-release upload \
            --owner $OWNER_NAME --repo $REPO_NAME \
            --tag "v${REL_VERSION}" \
            --release-name "petclinic v${REL_VERSION}" \
            --body "${RELEASE_BODY}" \
            --prerelease true \
            ${RELEASE_ARTIFACT[*]}