name: Build and deploy Pet Clinic App
on:
  push:
  workflow_dispatch:
jobs:
  iac:
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    runs-on: ubuntu-latest
    outputs:
      vm_ip: ${{ steps.tf_output.outputs.ip }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=petclinic" -backend-config="key=workflow.tfstate" -backend-config="access_key=${{ secrets.STORAGE_ACCOUNT_ACCESS_KEY }}"
        working-directory: terraform/as-is
      - name: Terraform Format
        id: fmt
        run: terraform fmt
      - name: terraform Validate
        id: validate
        run: terraform validate
        working-directory: terraform/as-is
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: terraform/as-is
      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outputs.stdout }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/as-is
      - name: Get outputs from Terraform
        id: tf_output
        working-directory: terraform/as-is
        run: |
          echo "::set-output name=ip::$(terraform output -raw public_ip)"
  deploy-tomcat-app:
    needs: iac
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn clean package
      - name: Check if the .war exists
        run: ls target
      - run: echo "VM IP ${{ needs.iac.outputs.vm_ip }}"
      - name: Copy war into the VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ needs.iac.outputs.vm_ip }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          source: "target/petclinic.war"
          target: "/tmp/petclinic"
      - name: Deploy .war in Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ needs.iac.outputs.vm_ip }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            sudo mv /tmp/petclinic/target/petclinic.war /opt/tomcat/latest/webapps/
